[2023-07-13 18:57:30,094] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: DAG_ETL_stock_data_google.extract_task scheduled__2023-07-12T00:00:00+00:00 [queued]>
[2023-07-13 18:57:30,104] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: DAG_ETL_stock_data_google.extract_task scheduled__2023-07-12T00:00:00+00:00 [queued]>
[2023-07-13 18:57:30,105] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 18:57:30,106] {taskinstance.py:1250} INFO - Starting attempt 3 of 3
[2023-07-13 18:57:30,107] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 18:57:30,125] {taskinstance.py:1270} INFO - Executing <Task(_PythonDecoratedOperator): extract_task> on 2023-07-12 00:00:00+00:00
[2023-07-13 18:57:30,130] {standard_task_runner.py:52} INFO - Started process 646 to run task
[2023-07-13 18:57:30,134] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'DAG_ETL_stock_data_google', 'extract_task', 'scheduled__2023-07-12T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/ETL_stock_data_google_DAG.py', '--cfg-path', '/tmp/tmplrndhjo2', '--error-file', '/tmp/tmpxe1x6gxa']
[2023-07-13 18:57:30,136] {standard_task_runner.py:80} INFO - Job 7: Subtask extract_task
[2023-07-13 18:57:30,260] {logging_mixin.py:109} INFO - Running <TaskInstance: DAG_ETL_stock_data_google.extract_task scheduled__2023-07-12T00:00:00+00:00 [running]> on host a917c5d777dc
[2023-07-13 18:57:30,372] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=fvinciguerra
AIRFLOW_CTX_DAG_ID=DAG_ETL_stock_data_google
AIRFLOW_CTX_TASK_ID=extract_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-12T00:00:00+00:00
[2023-07-13 18:57:30,375] {logging_mixin.py:109} INFO - Ejecutando Tarea 1: EXTRACT ======
[2023-07-13 18:57:31,530] {python.py:175} INFO - Done. Returned value was:                          Date        Open  ...  Stock Splits  Stock_Splits
0   2022-07-13 00:00:00-04:00  112.639000  ...           0.0             0
1   2022-07-14 00:00:00-04:00  110.825996  ...           0.0             0
2   2022-07-15 00:00:00-04:00  112.962997  ...           0.0             0
3   2022-07-18 00:00:00-04:00  113.440002  ...          20.0             0
4   2022-07-19 00:00:00-04:00  111.730003  ...           0.0             0
..                        ...         ...  ...           ...           ...
247 2023-07-07 00:00:00-04:00  120.889999  ...           0.0             0
248 2023-07-10 00:00:00-04:00  119.070000  ...           0.0             0
249 2023-07-11 00:00:00-04:00  116.760002  ...           0.0             0
250 2023-07-12 00:00:00-04:00  119.300003  ...           0.0             0
251 2023-07-13 00:00:00-04:00  121.540001  ...           0.0             0

[252 rows x 9 columns]
[2023-07-13 18:57:31,600] {xcom.py:447} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2023-07-13 18:57:31,604] {taskinstance.py:1743} WARNING - We expected to get frame set in local storage but it was not. Please report this as an issue with full logs at https://github.com/apache/***/issues/new
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1340, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1477, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1544, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2201, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 155, in set
    value=cls.serialize_value(value),
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 445, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/frozendict/__init__.py", line 32, in default
    return BaseJsonEncoder.default(self, obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1741, in get_truncated_error_traceback
    execution_frame = _TASK_EXECUTION_FRAME_LOCAL_STORAGE.frame
AttributeError: '_thread._local' object has no attribute 'frame'
[2023-07-13 18:57:31,610] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1340, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1477, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1544, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2201, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 155, in set
    value=cls.serialize_value(value),
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 445, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/frozendict/__init__.py", line 32, in default
    return BaseJsonEncoder.default(self, obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-07-13 18:57:31,635] {taskinstance.py:1278} INFO - Marking task as FAILED. dag_id=DAG_ETL_stock_data_google, task_id=extract_task, execution_date=20230712T000000, start_date=20230713T185730, end_date=20230713T185731
[2023-07-13 18:57:31,688] {standard_task_runner.py:93} ERROR - Failed to execute job 7 for task extract_task (Object of type DataFrame is not JSON serializable; 646)
[2023-07-13 18:57:31,725] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-07-13 18:57:31,809] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
