[2023-07-20T13:30:36.909+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_stock_data_google_DAG.dag_envio_error manual__2023-07-20T13:30:26.922768+00:00 [queued]>
[2023-07-20T13:30:37.076+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_stock_data_google_DAG.dag_envio_error manual__2023-07-20T13:30:26.922768+00:00 [queued]>
[2023-07-20T13:30:37.077+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-20T13:30:37.105+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): dag_envio_error> on 2023-07-20 13:30:26.922768+00:00
[2023-07-20T13:30:37.111+0000] {standard_task_runner.py:57} INFO - Started process 204 to run task
[2023-07-20T13:30:37.116+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_stock_data_google_DAG', 'dag_envio_error', 'manual__2023-07-20T13:30:26.922768+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/ETL_stock_data_google_DAG.py', '--cfg-path', '/tmp/tmpqn2nzk9l']
[2023-07-20T13:30:37.123+0000] {standard_task_runner.py:85} INFO - Job 74: Subtask dag_envio_error
[2023-07-20T13:30:37.217+0000] {task_command.py:410} INFO - Running <TaskInstance: ETL_stock_data_google_DAG.dag_envio_error manual__2023-07-20T13:30:26.922768+00:00 [running]> on host 90317fb99301
[2023-07-20T13:30:37.438+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fvinciguerra' AIRFLOW_CTX_DAG_ID='ETL_stock_data_google_DAG' AIRFLOW_CTX_TASK_ID='dag_envio_error' AIRFLOW_CTX_EXECUTION_DATE='2023-07-20T13:30:26.922768+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-20T13:30:26.922768+00:00'
[2023-07-20T13:30:40.248+0000] {logging_mixin.py:149} INFO - Exito al enviar el mail
[2023-07-20T13:30:40.253+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-07-20T13:30:40.288+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=ETL_stock_data_google_DAG, task_id=dag_envio_error, execution_date=20230720T133026, start_date=20230720T133036, end_date=20230720T133040
[2023-07-20T13:30:40.361+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-20T13:30:40.408+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
